[package]
name    = "gaia-qdrant-common"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp       = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
